
name: Jekyll Begin
markdown: redcarpet
#pygments: false
highlighter: pygments 

sass:
    sass_dir: _scss
    # style: expanded
css:
    css_dir: css

exclude: ["bower_components","foundation"]


# http_path = "/"
# css_dir: "css"
# sass_dir = "scss"
# images_dir = "images"
# javascripts_dir = "js"
